require_relative './quantity_definitions/basic'
require_relative './quantity_definitions/area_volume'
require_relative './quantity_definitions/velocity_acc_flow'
require_relative './quantity_definitions/force_power'
require_relative './quantity_definitions/energy'
require_relative './quantity_definitions/rotation'
require_relative './quantity_definitions/fluids'
require_relative './quantity_definitions/value'